apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secret-provider-class
spec:
  provider: aws
  secretObjects:
  - secretName: hugging-face-secret
    type: Opaque
    data:
    - objectName: hugging-face-secret
      key: token
  parameters:
    objects: |
      - objectName: "hugging-face-secret"
        objectType: "secretsmanager"
    usePodIdentity: "true"